### ISSUE TITLE
<TDS-Gaia: Auto Complete> Error 500 ao solicitar o autocomplete de um fonte com muitas linhas.

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-gaia#11]
> #### Funcionalidade:
> ```
> TDS-Gaia: Auto Complete
> ```
> 
>
> Ao pedir o autocomplete de um fonte com muitas linhas, me gera no log erro 500.
>
> Logs abaixo.
[tds-gaia-2024-09-10-17_39.log](https://github.com/user-attachments/files/16951962/tds-gaia-2024-09-10-17_39.log)

**Comment by brodao2** [comment]
Resolvido na release 0.0.13.
