### ISSUE TITLE
Token de Acesso

### ISSUE THREAD

**Issue by fnanttes** [totvs/tds-gaia#16]
Olá!

Instalei a extensão, fui logar e não tenho o TOKEN.
Como faço pra ter esse TOKEN?

**Comment by brodao2** [comment]
Ola @fnanttes 

Grato pelo seu interesse. O projeto encontra-se em fase piloto.
Caso seja um TOTVER, me chame no chat da TOTVS (acandido).
Caso contrário, solicito que tenha um pouco de paciência.

À disposição.

**Comment by fnanttes** [comment]
Olá! Boa tarde!

Ah! Entendi. Tudo bem...
Não sou TOTVER, mas gostaria de ser novamente... Hehehe

Até lá, vou aguardar. Obrigado!

Abraço!

Att,

Filipe Ferreira da Silva Nantes
Whatsapp: (19) 99925-2401
https://instabio.cc/ferilva1989


Em sex., 27 de set. de 2024 às 10:22, Alan Candido ***@***.***>
escreveu:
