### ISSUE TITLE
Login - Onde conseguir o token

### ISSUE THREAD

**Issue by jerfweb** [totvs/tds-gaia#20]
Prezados,

Onde conseguimos o token para login da ferramenta?
Na documentação não deixa claro essa informação.

**Comment by brodao2** [comment]
@jerfweb,

Grato pelo seu interesse. O projeto encontra-se em fase piloto.
Caso seja um TOTVER, me chame no chat da TOTVS (acandido).
Caso contrário, solicito que tenha um pouco de paciência.

À disposição.
